export const GET_COLLECTION_BY_HANDLE_REQUESTED = 'GET_COLLECTION_BY_HANDLE_REQUESTED';
export const GET_COLLECTION_BY_HANDLE_SUCCEEDED = 'GET_COLLECTION_BY_HANDLE_SUCCEEDED';
export const GET_COLLECTION_BY_HANDLE_FAILED = 'GET_COLLECTION_BY_HANDLE_FAILED';

export const CLEAR_COLLECTION_REQUESTED = 'CLEAR_COLLECTION_REQUESTED';
export const CLEAR_COLLECTION_SUCCEEDED = 'CLEAR_COLLECTION_SUCCEEDED';
export const CLEAR_COLLECTION_FAILED = 'CLEAR_COLLECTION_FAILED';

export const GET_APPAREL_COLLECTIONS_REQUESTED = 'GET_APPAREL_COLLECTIONS_REQUESTED';
export const GET_APPAREL_COLLECTIONS_SUCCEEDED = 'GET_APPAREL_COLLECTIONS_SUCCEEDED';
export const GET_APPAREL_COLLECTIONS_FAILED = 'GET_APPAREL_COLLECTIONS_FAILED';

export const GET_ACCESSORIES_COLLECTIONS_REQUESTED = 'GET_ACCESSORIES_COLLECTIONS_REQUESTED';
export const GET_ACCESSORIES_COLLECTIONS_SUCCEEDED = 'GET_ACCESSORIES_COLLECTIONS_SUCCEEDED';
export const GET_ACCESSORIES_COLLECTIONS_FAILED = 'GET_ACCESSORIES_COLLECTIONS_FAILED';

export const GET_FEATURED_COLLECTIONS_REQUESTED = 'GET_FEATURED_COLLECTIONS_REQUESTED';
export const GET_FEATURED_COLLECTIONS_SUCCEEDED = 'GET_FEATURED_COLLECTIONS_SUCCEEDED';
export const GET_FEATURED_COLLECTIONS_FAILED = 'GET_FEATURED_COLLECTIONS_FAILED';

export const GET_FILTERED_COLLECTION_PRODUCTS_REQUESTED = 'GET_FILTERED_COLLECTION_PRODUCTS_REQUESTED';
export const GET_FILTERED_COLLECTION_PRODUCTS_SUCCEEDED = 'GET_FILTERED_COLLECTION_PRODUCTS_SUCCEEDED';
export const GET_FILTERED_COLLECTION_PRODUCTS_FAILED = 'GET_FILTERED_COLLECTION_PRODUCTS_FAILED';

export const CLEAR_FILTERED_COLLECTION_PRODUCTS_REQUESTED = 'CLEAR_FILTERED_COLLECTION_PRODUCTS_REQUESTED';
export const CLEAR_FILTERED_COLLECTION_PRODUCTS_SUCCEEDED = 'CLEAR_FILTERED_COLLECTION_PRODUCTS_SUCCEEDED';
export const CLEAR_FILTERED_COLLECTION_PRODUCTS_FAILED = 'CLEAR_FILTERED_COLLECTION_PRODUCTS_FAILED';

export const getCollectionByHandle = (collectionHandle) => ({
  type: GET_COLLECTION_BY_HANDLE_REQUESTED,
  collectionHandle
});

export const receiveCollectionByHandle = (payload) => ({
  type: GET_COLLECTION_BY_HANDLE_SUCCEEDED,
  payload
});

export const clearCollection = (payload) => {
  return {
    type: CLEAR_COLLECTION_REQUESTED,
    payload
  };
};

export const getApparelCollections = () => ({
  type: GET_APPAREL_COLLECTIONS_REQUESTED,
});

export const receiveApparelCollections = (payload) => ({
  type: GET_APPAREL_COLLECTIONS_SUCCEEDED,
  payload
});

export const getAccessoriesCollections = () => ({
  type: GET_ACCESSORIES_COLLECTIONS_REQUESTED,
});

export const receiveAccessoriesCollections = (payload) => ({
  type: GET_ACCESSORIES_COLLECTIONS_SUCCEEDED,
  payload
});

export const getFeaturedCollections = () => ({
  type: GET_FEATURED_COLLECTIONS_REQUESTED,
});

export const receiveFeaturedCollections = (payload) => ({
  type: GET_FEATURED_COLLECTIONS_SUCCEEDED,
  payload
});

export const getFilteredCollectionProducts = (filteredProducts) => ({
  type: GET_FILTERED_COLLECTION_PRODUCTS_REQUESTED,
  filteredProducts
});

export const receiveFilteredCollectionProducts = (payload) => ({
  type: GET_FILTERED_COLLECTION_PRODUCTS_SUCCEEDED,
  payload
});

export const clearFilteredCollectionProducts = (payload) => {
  return {
    type: CLEAR_FILTERED_COLLECTION_PRODUCTS_REQUESTED,
    payload
  };
};